version: '3'

services:
  frontend:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
